const CONSTANTS = {
    SET_LOADING   : 'SET_LOADING',
    STOP_LOADING  : 'STOP_LOADING',
    GET_PRODUCTS  : 'GET_PRODUCTS',
    SHOW_OTHERS_PRODUCTS : 'SHOW_OTHERS_PRODUCTS',
    HIDE_OTHERS_PRODUCTS  : 'HIDE_OTHERS_PRODUCTS'
};

export default CONSTANTS;